// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_pathinfo.proto

#include "rpc_pathinfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace tvix {
namespace store {
namespace v1 {
PROTOBUF_CONSTEXPR GetPathInfoRequest::GetPathInfoRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.by_what_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct GetPathInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetPathInfoRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetPathInfoRequestDefaultTypeInternal() {}
  union {
    GetPathInfoRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetPathInfoRequestDefaultTypeInternal _GetPathInfoRequest_default_instance_;
PROTOBUF_CONSTEXPR ListPathInfoRequest::ListPathInfoRequest(
    ::_pbi::ConstantInitialized) {}
struct ListPathInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListPathInfoRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListPathInfoRequestDefaultTypeInternal() {}
  union {
    ListPathInfoRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListPathInfoRequestDefaultTypeInternal _ListPathInfoRequest_default_instance_;
PROTOBUF_CONSTEXPR CalculateNARResponse::CalculateNARResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nar_sha256_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.nar_size_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CalculateNARResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculateNARResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculateNARResponseDefaultTypeInternal() {}
  union {
    CalculateNARResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculateNARResponseDefaultTypeInternal _CalculateNARResponse_default_instance_;
}  // namespace v1
}  // namespace store
}  // namespace tvix
static ::_pb::Metadata file_level_metadata_rpc_5fpathinfo_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_rpc_5fpathinfo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rpc_5fpathinfo_2eproto = nullptr;

const uint32_t TableStruct_rpc_5fpathinfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::GetPathInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::GetPathInfoRequest, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::GetPathInfoRequest, _impl_.by_what_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::ListPathInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::CalculateNARResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::CalculateNARResponse, _impl_.nar_size_),
  PROTOBUF_FIELD_OFFSET(::tvix::store::v1::CalculateNARResponse, _impl_.nar_sha256_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::tvix::store::v1::GetPathInfoRequest)},
  { 8, -1, -1, sizeof(::tvix::store::v1::ListPathInfoRequest)},
  { 14, -1, -1, sizeof(::tvix::store::v1::CalculateNARResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::tvix::store::v1::_GetPathInfoRequest_default_instance_._instance,
  &::tvix::store::v1::_ListPathInfoRequest_default_instance_._instance,
  &::tvix::store::v1::_CalculateNARResponse_default_instance_._instance,
};

const char descriptor_table_protodef_rpc_5fpathinfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022rpc_pathinfo.proto\022\rtvix.store.v1\032\016pat"
  "hinfo.proto\"9\n\022GetPathInfoRequest\022\030\n\016by_"
  "output_hash\030\001 \001(\014H\000B\t\n\007by_what\"\025\n\023ListPa"
  "thInfoRequest\"<\n\024CalculateNARResponse\022\020\n"
  "\010nar_size\030\001 \001(\004\022\022\n\nnar_sha256\030\002 \001(\0142\236\002\n\017"
  "PathInfoService\022A\n\003Get\022!.tvix.store.v1.G"
  "etPathInfoRequest\032\027.tvix.store.v1.PathIn"
  "fo\0227\n\003Put\022\027.tvix.store.v1.PathInfo\032\027.tvi"
  "x.store.v1.PathInfo\022H\n\014CalculateNAR\022\023.tv"
  "ix.store.v1.Node\032#.tvix.store.v1.Calcula"
  "teNARResponse\022E\n\004List\022\".tvix.store.v1.Li"
  "stPathInfoRequest\032\027.tvix.store.v1.PathIn"
  "fo0\001B(Z&code.tvl.fyi/tvix/store/protos;s"
  "torev1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_rpc_5fpathinfo_2eproto_deps[1] = {
  &::descriptor_table_pathinfo_2eproto,
};
static ::_pbi::once_flag descriptor_table_rpc_5fpathinfo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rpc_5fpathinfo_2eproto = {
    false, false, 534, descriptor_table_protodef_rpc_5fpathinfo_2eproto,
    "rpc_pathinfo.proto",
    &descriptor_table_rpc_5fpathinfo_2eproto_once, descriptor_table_rpc_5fpathinfo_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_rpc_5fpathinfo_2eproto::offsets,
    file_level_metadata_rpc_5fpathinfo_2eproto, file_level_enum_descriptors_rpc_5fpathinfo_2eproto,
    file_level_service_descriptors_rpc_5fpathinfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rpc_5fpathinfo_2eproto_getter() {
  return &descriptor_table_rpc_5fpathinfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rpc_5fpathinfo_2eproto(&descriptor_table_rpc_5fpathinfo_2eproto);
namespace tvix {
namespace store {
namespace v1 {

// ===================================================================

class GetPathInfoRequest::_Internal {
 public:
};

GetPathInfoRequest::GetPathInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tvix.store.v1.GetPathInfoRequest)
}
GetPathInfoRequest::GetPathInfoRequest(const GetPathInfoRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetPathInfoRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.by_what_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_by_what();
  switch (from.by_what_case()) {
    case kByOutputHash: {
      _this->_internal_set_by_output_hash(from._internal_by_output_hash());
      break;
    }
    case BY_WHAT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:tvix.store.v1.GetPathInfoRequest)
}

inline void GetPathInfoRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.by_what_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_by_what();
}

GetPathInfoRequest::~GetPathInfoRequest() {
  // @@protoc_insertion_point(destructor:tvix.store.v1.GetPathInfoRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetPathInfoRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_by_what()) {
    clear_by_what();
  }
}

void GetPathInfoRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetPathInfoRequest::clear_by_what() {
// @@protoc_insertion_point(one_of_clear_start:tvix.store.v1.GetPathInfoRequest)
  switch (by_what_case()) {
    case kByOutputHash: {
      _impl_.by_what_.by_output_hash_.Destroy();
      break;
    }
    case BY_WHAT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BY_WHAT_NOT_SET;
}


void GetPathInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:tvix.store.v1.GetPathInfoRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_by_what();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetPathInfoRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes by_output_hash = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_by_output_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetPathInfoRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tvix.store.v1.GetPathInfoRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes by_output_hash = 1;
  if (_internal_has_by_output_hash()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_by_output_hash(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tvix.store.v1.GetPathInfoRequest)
  return target;
}

size_t GetPathInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tvix.store.v1.GetPathInfoRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (by_what_case()) {
    // bytes by_output_hash = 1;
    case kByOutputHash: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_by_output_hash());
      break;
    }
    case BY_WHAT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetPathInfoRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetPathInfoRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetPathInfoRequest::GetClassData() const { return &_class_data_; }


void GetPathInfoRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetPathInfoRequest*>(&to_msg);
  auto& from = static_cast<const GetPathInfoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tvix.store.v1.GetPathInfoRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.by_what_case()) {
    case kByOutputHash: {
      _this->_internal_set_by_output_hash(from._internal_by_output_hash());
      break;
    }
    case BY_WHAT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetPathInfoRequest::CopyFrom(const GetPathInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tvix.store.v1.GetPathInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetPathInfoRequest::IsInitialized() const {
  return true;
}

void GetPathInfoRequest::InternalSwap(GetPathInfoRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.by_what_, other->_impl_.by_what_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetPathInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_5fpathinfo_2eproto_getter, &descriptor_table_rpc_5fpathinfo_2eproto_once,
      file_level_metadata_rpc_5fpathinfo_2eproto[0]);
}

// ===================================================================

class ListPathInfoRequest::_Internal {
 public:
};

ListPathInfoRequest::ListPathInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:tvix.store.v1.ListPathInfoRequest)
}
ListPathInfoRequest::ListPathInfoRequest(const ListPathInfoRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ListPathInfoRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tvix.store.v1.ListPathInfoRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListPathInfoRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListPathInfoRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ListPathInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_5fpathinfo_2eproto_getter, &descriptor_table_rpc_5fpathinfo_2eproto_once,
      file_level_metadata_rpc_5fpathinfo_2eproto[1]);
}

// ===================================================================

class CalculateNARResponse::_Internal {
 public:
};

CalculateNARResponse::CalculateNARResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tvix.store.v1.CalculateNARResponse)
}
CalculateNARResponse::CalculateNARResponse(const CalculateNARResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CalculateNARResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.nar_sha256_){}
    , decltype(_impl_.nar_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.nar_sha256_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nar_sha256_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_nar_sha256().empty()) {
    _this->_impl_.nar_sha256_.Set(from._internal_nar_sha256(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.nar_size_ = from._impl_.nar_size_;
  // @@protoc_insertion_point(copy_constructor:tvix.store.v1.CalculateNARResponse)
}

inline void CalculateNARResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.nar_sha256_){}
    , decltype(_impl_.nar_size_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.nar_sha256_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.nar_sha256_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CalculateNARResponse::~CalculateNARResponse() {
  // @@protoc_insertion_point(destructor:tvix.store.v1.CalculateNARResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CalculateNARResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nar_sha256_.Destroy();
}

void CalculateNARResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CalculateNARResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tvix.store.v1.CalculateNARResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nar_sha256_.ClearToEmpty();
  _impl_.nar_size_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CalculateNARResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 nar_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.nar_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes nar_sha256 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_nar_sha256();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CalculateNARResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tvix.store.v1.CalculateNARResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 nar_size = 1;
  if (this->_internal_nar_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_nar_size(), target);
  }

  // bytes nar_sha256 = 2;
  if (!this->_internal_nar_sha256().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_nar_sha256(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tvix.store.v1.CalculateNARResponse)
  return target;
}

size_t CalculateNARResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tvix.store.v1.CalculateNARResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes nar_sha256 = 2;
  if (!this->_internal_nar_sha256().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_nar_sha256());
  }

  // uint64 nar_size = 1;
  if (this->_internal_nar_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_nar_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CalculateNARResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CalculateNARResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CalculateNARResponse::GetClassData() const { return &_class_data_; }


void CalculateNARResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CalculateNARResponse*>(&to_msg);
  auto& from = static_cast<const CalculateNARResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tvix.store.v1.CalculateNARResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nar_sha256().empty()) {
    _this->_internal_set_nar_sha256(from._internal_nar_sha256());
  }
  if (from._internal_nar_size() != 0) {
    _this->_internal_set_nar_size(from._internal_nar_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CalculateNARResponse::CopyFrom(const CalculateNARResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tvix.store.v1.CalculateNARResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalculateNARResponse::IsInitialized() const {
  return true;
}

void CalculateNARResponse::InternalSwap(CalculateNARResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.nar_sha256_, lhs_arena,
      &other->_impl_.nar_sha256_, rhs_arena
  );
  swap(_impl_.nar_size_, other->_impl_.nar_size_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CalculateNARResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rpc_5fpathinfo_2eproto_getter, &descriptor_table_rpc_5fpathinfo_2eproto_once,
      file_level_metadata_rpc_5fpathinfo_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace store
}  // namespace tvix
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tvix::store::v1::GetPathInfoRequest*
Arena::CreateMaybeMessage< ::tvix::store::v1::GetPathInfoRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tvix::store::v1::GetPathInfoRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::tvix::store::v1::ListPathInfoRequest*
Arena::CreateMaybeMessage< ::tvix::store::v1::ListPathInfoRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tvix::store::v1::ListPathInfoRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::tvix::store::v1::CalculateNARResponse*
Arena::CreateMaybeMessage< ::tvix::store::v1::CalculateNARResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tvix::store::v1::CalculateNARResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
